# Generated by Django 3.0.7 on 2020-06-23 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='мова програмування')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'мова програмування',
                'verbose_name_plural': 'мови програмування',
            },
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'назва населеного пункту', 'verbose_name_plural': 'назва населених пунктів'},
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='назва населеного пункту'),
        ),
    ]
