# Generated by Django 3.0.7 on 2020-06-23 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0002_auto_20200623_2343'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('title', models.CharField(max_length=250, verbose_name='заголовок вакансії')),
                ('company', models.CharField(max_length=250, verbose_name='компанія')),
                ('description', models.TextField(verbose_name='опис вакансії')),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='scraping.City', verbose_name='місто')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraping.Language', verbose_name='мова програмування')),
            ],
            options={
                'verbose_name': 'вакансія',
                'verbose_name_plural': 'вакансії',
                'ordering': ['-timestamp'],
            },
        ),
    ]
