# Generated by Django 3.0.7 on 2020-07-01 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'verbose_name': 'аккаунт', 'verbose_name_plural': 'аккаунти'},
        ),
    ]
